apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imagen
  labels:
    app: imagen
spec:
  serviceName: imagen
  replicas: 1
  selector:
    matchLabels:
      app: imagen
  template:
    metadata:
      labels:
        app: imagen
    spec:
      containers:
        - name: imagen
          image: dofer123/imagen:latest-aarch64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          envFrom:
            - secretRef:
                name: pok-secrets
          volumeMounts:
            - name: new-cards-volume
              mountPath: /app/newCards
      volumes:
        - name: new-cards-volume
          persistentVolumeClaim:
            claimName: new-cards-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: imagen
  labels:
    app: imagen
spec:
  selector:
    app: imagen
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
