apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: imagen
  labels:
    app: imagen
spec:
  serviceName: imagen
  replicas: 1
  selector:
    matchLabels:
      app: imagen
  template:
    metadata:
      labels:
        app: imagen
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: imagen
          image: dofer123/imagen:latest-x86_64
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: pok-secrets
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - name: new-cards-volume
              mountPath: /app/newCards
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      restartPolicy: Always
      volumes:
        - name: new-cards-volume
          persistentVolumeClaim:
            claimName: new-cards-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: imagen
  labels:
    app: imagen
spec:
  selector:
    app: imagen
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
